version: '3.8' 

volumes:
  db: {}
 
services: 
  app: 
    build: .
    command: ["-dsn", "/root/tdispo.db", "-session-key", "${key}"]
    volumes:
      - db:/root
    labels: 
      - traefik.enable=true 
      - traefik.http.routers.nginx.rule=Host(`${url}`) 
      - traefik.http.routers.nginx.entrypoints=web,websecure 
      - traefik.http.routers.nginx.middlewares=redirect-to-https@file
